[workspace]

members = [
  # Ordering here apparently defines release order:
  "tower-gcra",
]
resolver = "3"

[patch.crates-io]
governor = { version = "=0.10.4", git = "https://github.com/sp1ff/governor.git", branch = "issue-193"}
