# Need to keep this in sync with Cargo.toml!
edition = "2024"
reorder_imports = true
# Argh... still unstable; cf. https://github.com/rust-lang/rustfmt/issues/5083
# group_imports = "StdExternalCrate"
# Argh... still unstable; cf. https://github.com/rust-lang/rustfmt/issues/4991
# imports_granularity = "Crate"
